server:
  servlet:
    session:
      timeout: 30m

spring:
  data:
    redis:
#      url: redis://default:cvcOi1y9TzELEEKRriSjY5YFrp93VI4Q@redis-16267.c302.asia-northeast1-1.gce.cloud.redislabs.com:16267
#      host: redis-16267.c302.asia-northeast1-1.gce.cloud.redislabs.com
#      port: 16267
#      username: default
#      password: cvcOi1y9TzELEEKRriSjY5YFrp93VI4Q
    mongodb:
#      uri: mongodb+srv://marvel:aAadVk2kmrKACVbS@cluster0.iip4m.mongodb.net
      uri: mongodb+srv://quanphamlsc:quan_2002@chatbot.trqhh6o.mongodb.net
      database: ground
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session
  security:
    oauth2:
      client:
        provider:
          discord:
            authorization-uri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: username
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          google:
            client-id: 717048204630-tphrgp3hfn1fheiehrtrfv9hijc5m4gf.apps.googleusercontent.com
            client-secret: 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
#            scope:
#              - email
#              - username
          facebook:
            client-id: 595915086007723
            client-secret: 60d39926cc65a63bf5a29c680a4a3b65
          github:
            client-id: b3ba56d913a709f1f4bd
            client-secret: df683653dd3ad3ca9870ddcfc6b37f1fa54e2aa2
          discord:
            client-id: 1130348384830631987
            client-secret: iw1zrAJ7W908yMelz0RisjfHcrRNBQDM
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - identify
          kakao:
            client-id: 939811
            client-secret: 16400776238a35d4d7dccaab559745c8
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            scope:
              - profile
              - account_email
          naver:
            client-id: JVvx7zP_OmxSXQWVbNnD
            client-secret: cOwe2G23kI
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image


#          github:
#            client-id: f4738ba18a6630bf3a40
#            client-secret: 9c4d1203c8fbe058c921d7531cabc6b06d2ac63a
#          discord:
#            client-id: 847959809475215380
#            client-secret: ihKGVKtR-ttU9XT4QFsBmf1dLymuAPHa
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - identify
#          kakao:
#            client-id: your-kakao-client-id
#            client-secret: your-kakao-client-secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-authentication-method: POST
#            scope:
#              - profile
#              - account_email
#          naver:
#            client-id: your-naver-client-id
#            client-secret: your-naver-client-secret
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            scope:
#              - name
#              - email
#              - profile_image
  mustache:
    suffix: .html